apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "baby-names.fullname" . }}-migration-{{ .Release.Revision }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baby-names.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "baby-names.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      shareProcessNamespace: true
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: migration
        image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
        env:
        - name: LIQUIBASE_COMMAND_URL
          value: "jdbc:postgresql://{{ .Values.migration.env.DB_HOST }}:{{ .Values.migration.env.DB_PORT }}/{{ .Values.migration.env.DB_NAME }}"
        - name: LIQUIBASE_COMMAND_USERNAME
          value: "{{ .Values.migration.env.DB_USER }}"
        {{- if ne .Values.migration.env.DB_IAM_AUTH "true" }}
        - name: LIQUIBASE_COMMAND_PASSWORD
          value: "{{ .Values.migration.env.DB_PASSWORD }}"
        {{- end }}
        resources:
          {{- toYaml .Values.migration.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.migration.securityContext | nindent 10 }}
      {{- if .Values.database.iamAuth }}
      {{- include "baby-names.cloudsql-proxy" . | nindent 6 }}
      {{- end }}
